/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActiveTimerState {
  'startTime' : bigint,
  'pausedAt' : [] | [bigint],
  'userId' : Principal,
  'isPaused' : boolean,
  'side' : { 'left' : null } |
    { 'right' : null },
  'totalPausedDuration' : bigint,
  'childId' : string,
}
export interface BreastfeedingSession {
  'startTime' : bigint,
  'duration' : bigint,
  'side' : { 'left' : null } |
    { 'right' : null },
  'childId' : string,
}
export interface ChildProfileView {
  'id' : string,
  'birthDate' : bigint,
  'name' : string,
  'sharedWith' : Array<Principal>,
  'isPublic' : boolean,
  'photo' : [] | [ExternalBlob],
  'parent' : Principal,
}
export interface DiaperLog {
  'contents' : { 'tuscia' : boolean, 'kakis' : boolean, 'sysius' : boolean },
  'childId' : string,
  'timestamp' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface JournalNote {
  'createdAt' : bigint,
  'color' : NoteColor,
  'text' : string,
  'childId' : string,
  'updatedAt' : bigint,
}
export type NoteColor = { 'blue' : null } |
  { 'pink' : null } |
  { 'purple' : null } |
  { 'green' : null } |
  { 'yellow' : null };
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export type Time = bigint;
export interface TummyTimeSession {
  'startTime' : bigint,
  'duration' : bigint,
  'childId' : string,
}
export interface TummyTimeTimerState {
  'startTime' : bigint,
  'pausedAt' : [] | [bigint],
  'userId' : Principal,
  'isPaused' : boolean,
  'totalPausedDuration' : bigint,
  'childId' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeightEntry {
  'weight' : number,
  'childId' : string,
  'weightId' : string,
  'timestamp' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptChildInvite' : ActorMethod<[string], undefined>,
  'addChild' : ActorMethod<
    [string, bigint, [] | [ExternalBlob], boolean],
    string
  >,
  'addJournalNote' : ActorMethod<[string, string, NoteColor], undefined>,
  'addManualBreastfeedingSession' : ActorMethod<
    [string, bigint, bigint, { 'left' : null } | { 'right' : null }],
    undefined
  >,
  'addWeightEntry' : ActorMethod<[string, number, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateAgeInDays' : ActorMethod<[string], bigint>,
  'completeBreastfeedingSession' : ActorMethod<[string], undefined>,
  'completeTummyTimeSession' : ActorMethod<[string], undefined>,
  'deleteJournalNote' : ActorMethod<[string, string], undefined>,
  'deleteWeightEntry' : ActorMethod<[string, string], undefined>,
  'generateChildInviteLink' : ActorMethod<[string], string>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getActiveBreastfeedingTimer' : ActorMethod<
    [string],
    [] | [ActiveTimerState]
  >,
  'getActiveTummyTimeTimer' : ActorMethod<[string], [] | [TummyTimeTimerState]>,
  'getAllPublicChildren' : ActorMethod<[], Array<ChildProfileView>>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getBreastfeedingSessionsForChild' : ActorMethod<
    [string],
    Array<BreastfeedingSession>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChild' : ActorMethod<[string], ChildProfileView>,
  'getChildStatistics' : ActorMethod<
    [string],
    {
      'totalDiapers' : bigint,
      'totalBreastfeedingSessions' : bigint,
      'totalTummyTime' : bigint,
    }
  >,
  'getChildrenByParent' : ActorMethod<[Principal], Array<ChildProfileView>>,
  'getDiaperLogsForChild' : ActorMethod<[string], Array<DiaperLog>>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getJournalNotesForChild' : ActorMethod<[string], Array<JournalNote>>,
  'getSharedChildren' : ActorMethod<[], Array<ChildProfileView>>,
  'getSharedUsers' : ActorMethod<[string], Array<Principal>>,
  'getTummyTimeSessionsForChild' : ActorMethod<
    [string],
    Array<TummyTimeSession>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeightEntriesForChild' : ActorMethod<[string], Array<WeightEntry>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logDiaperChange' : ActorMethod<
    [string, boolean, boolean, boolean],
    undefined
  >,
  'pauseBreastfeedingTimer' : ActorMethod<[string], undefined>,
  'pauseTummyTimeTimer' : ActorMethod<[string], undefined>,
  'regenerateChildPhoto' : ActorMethod<[string], undefined>,
  'resumeBreastfeedingTimer' : ActorMethod<[string], undefined>,
  'resumeTummyTimeTimer' : ActorMethod<[string], undefined>,
  'revokeChildAccess' : ActorMethod<[string, Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchJournalNotes' : ActorMethod<[string, string], Array<JournalNote>>,
  'shareChildWithUser' : ActorMethod<[string, Principal], undefined>,
  'startBreastfeedingSession' : ActorMethod<
    [string, { 'left' : null } | { 'right' : null }],
    undefined
  >,
  'startTummyTimeSession' : ActorMethod<[string], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'toggleChildVisibility' : ActorMethod<[string], undefined>,
  'updateJournalNote' : ActorMethod<
    [string, string, string, [] | [NoteColor]],
    undefined
  >,
  'updateWeightEntry' : ActorMethod<
    [string, string, number, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];