/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ChildProfileView {
    id: string;
    birthDate: bigint;
    name: string;
    sharedWith: Array<Principal>;
    isPublic: boolean;
    photo?: ExternalBlob;
    parent: Principal;
}
export type Time = bigint;
export interface TummyTimeSession {
    startTime: bigint;
    duration: bigint;
    childId: string;
}
export interface TummyTimeTimerState {
    startTime: bigint;
    pausedAt?: bigint;
    userId: Principal;
    isPaused: boolean;
    totalPausedDuration: bigint;
    childId: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface DiaperLog {
    contents: {
        tuscia: boolean;
        kakis: boolean;
        sysius: boolean;
    };
    childId: string;
    timestamp: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface BreastfeedingSession {
    startTime: bigint;
    duration: bigint;
    side: Variant_left_right;
    childId: string;
}
export interface JournalNote {
    createdAt: bigint;
    color: NoteColor;
    text: string;
    childId: string;
    updatedAt: bigint;
}
export interface InviteCode {
    created: Time;
    code: string;
    used: boolean;
}
export interface RSVP {
    name: string;
    inviteCode: string;
    timestamp: Time;
    attending: boolean;
}
export interface ActiveTimerState {
    startTime: bigint;
    pausedAt?: bigint;
    userId: Principal;
    isPaused: boolean;
    side: Variant_left_right;
    totalPausedDuration: bigint;
    childId: string;
}
export interface WeightEntry {
    weight: number;
    childId: string;
    weightId: string;
    timestamp: bigint;
}
export enum PumpSide {
    left = "left",
    right = "right",
    both = "both"
}
export interface MilkPumpingSession {
    sessionId: string;
    childId: string;
    timestamp: bigint;
    mlAmount: number;
    side: PumpSide;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum NoteColor {
    blue = "blue",
    pink = "pink",
    purple = "purple",
    green = "green",
    yellow = "yellow"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_left_right {
    left = "left",
    right = "right"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptChildInvite(inviteCode: string): Promise<void>;
    addChild(name: string, birthDate: bigint, photo: ExternalBlob | null, isPublic: boolean): Promise<string>;
    addJournalNote(childId: string, text: string, color: NoteColor): Promise<void>;
    addManualBreastfeedingSession(childId: string, date: bigint, duration: bigint, side: Variant_left_right): Promise<void>;
    addWeightEntry(childId: string, weight: number, timestamp: bigint): Promise<void>;
    addMilkPumpingSession(childId: string, timestamp: bigint, mlAmount: number, side: { left: null } | { right: null } | { both: null }): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    calculateAgeInDays(childId: string): Promise<bigint>;
    completeBreastfeedingSession(childId: string): Promise<void>;
    completeTummyTimeSession(childId: string): Promise<void>;
    deleteJournalNote(childId: string, noteId: string): Promise<void>;
    deleteWeightEntry(childId: string, weightId: string): Promise<void>;
    deleteMilkPumpingSession(childId: string, sessionId: string): Promise<void>;
    generateChildInviteLink(childId: string): Promise<string>;
    generateInviteCode(): Promise<string>;
    getActiveBreastfeedingTimer(childId: string): Promise<ActiveTimerState | null>;
    getActiveTummyTimeTimer(childId: string): Promise<TummyTimeTimerState | null>;
    getAllPublicChildren(): Promise<Array<ChildProfileView>>;
    getAllRSVPs(): Promise<Array<RSVP>>;
    getBreastfeedingSessionsForChild(childId: string): Promise<Array<BreastfeedingSession>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChild(childId: string): Promise<ChildProfileView>;
    getChildStatistics(childId: string): Promise<{
        totalDiapers: bigint;
        totalBreastfeedingSessions: bigint;
        totalTummyTime: bigint;
    }>;
    getChildrenByParent(parent: Principal): Promise<Array<ChildProfileView>>;
    getDiaperLogsForChild(childId: string): Promise<Array<DiaperLog>>;
    getInviteCodes(): Promise<Array<InviteCode>>;
    getJournalNotesForChild(childId: string): Promise<Array<JournalNote>>;
    getSharedChildren(): Promise<Array<ChildProfileView>>;
    getSharedUsers(childId: string): Promise<Array<Principal>>;
    getTummyTimeSessionsForChild(childId: string): Promise<Array<TummyTimeSession>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWeightEntriesForChild(childId: string): Promise<Array<WeightEntry>>;
    getMilkPumpingSessionsForChild(childId: string): Promise<Array<MilkPumpingSession>>;
    isCallerAdmin(): Promise<boolean>;
    logDiaperChange(childId: string, kakis: boolean, sysius: boolean, tuscia: boolean): Promise<void>;
    pauseBreastfeedingTimer(childId: string): Promise<void>;
    pauseTummyTimeTimer(childId: string): Promise<void>;
    regenerateChildPhoto(childId: string): Promise<void>;
    resumeBreastfeedingTimer(childId: string): Promise<void>;
    resumeTummyTimeTimer(childId: string): Promise<void>;
    revokeChildAccess(childId: string, userId: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchJournalNotes(childId: string, searchTerm: string): Promise<Array<JournalNote>>;
    shareChildWithUser(childId: string, userId: Principal): Promise<void>;
    startBreastfeedingSession(childId: string, side: Variant_left_right): Promise<void>;
    startTummyTimeSession(childId: string): Promise<void>;
    submitRSVP(name: string, attending: boolean, inviteCode: string): Promise<void>;
    toggleChildVisibility(childId: string): Promise<void>;
    updateJournalNote(childId: string, noteId: string, newText: string, newColor: NoteColor | null): Promise<void>;
    updateWeightEntry(childId: string, weightId: string, newWeight: number, newTimestamp: bigint): Promise<void>;
}
import type { ActiveTimerState as _ActiveTimerState, BreastfeedingSession as _BreastfeedingSession, ChildProfileView as _ChildProfileView, ExternalBlob as _ExternalBlob, JournalNote as _JournalNote, NoteColor as _NoteColor, TummyTimeTimerState as _TummyTimeTimerState, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptChildInvite(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptChildInvite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptChildInvite(arg0);
            return result;
        }
    }
    async addChild(arg0: string, arg1: bigint, arg2: ExternalBlob | null, arg3: boolean): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addChild(arg0, arg1, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChild(arg0, arg1, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async addJournalNote(arg0: string, arg1: string, arg2: NoteColor): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addJournalNote(arg0, arg1, to_candid_NoteColor_n10(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJournalNote(arg0, arg1, to_candid_NoteColor_n10(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addManualBreastfeedingSession(arg0: string, arg1: bigint, arg2: bigint, arg3: Variant_left_right): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addManualBreastfeedingSession(arg0, arg1, arg2, to_candid_variant_n12(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addManualBreastfeedingSession(arg0, arg1, arg2, to_candid_variant_n12(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async addWeightEntry(arg0: string, arg1: number, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWeightEntry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWeightEntry(arg0, arg1, arg2);
            return result;
        }
    }
    async addMilkPumpingSession(arg0: string, arg1: bigint, arg2: number, arg3: { left: null } | { right: null } | { both: null }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMilkPumpingSession(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMilkPumpingSession(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculateAgeInDays(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateAgeInDays(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateAgeInDays(arg0);
            return result;
        }
    }
    async completeBreastfeedingSession(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeBreastfeedingSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeBreastfeedingSession(arg0);
            return result;
        }
    }
    async completeTummyTimeSession(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeTummyTimeSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeTummyTimeSession(arg0);
            return result;
        }
    }
    async deleteJournalNote(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJournalNote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJournalNote(arg0, arg1);
            return result;
        }
    }
    async deleteWeightEntry(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWeightEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWeightEntry(arg0, arg1);
            return result;
        }
    }
    async deleteMilkPumpingSession(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMilkPumpingSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMilkPumpingSession(arg0, arg1);
            return result;
        }
    }
    async generateChildInviteLink(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateChildInviteLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateChildInviteLink(arg0);
            return result;
        }
    }
    async generateInviteCode(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateInviteCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateInviteCode();
            return result;
        }
    }
    async getActiveBreastfeedingTimer(arg0: string): Promise<ActiveTimerState | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveBreastfeedingTimer(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveBreastfeedingTimer(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveTummyTimeTimer(arg0: string): Promise<TummyTimeTimerState | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveTummyTimeTimer(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveTummyTimeTimer(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPublicChildren(): Promise<Array<ChildProfileView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublicChildren();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublicChildren();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRSVPs(): Promise<Array<RSVP>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRSVPs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRSVPs();
            return result;
        }
    }
    async getBreastfeedingSessionsForChild(arg0: string): Promise<Array<BreastfeedingSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBreastfeedingSessionsForChild(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBreastfeedingSessionsForChild(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChild(arg0: string): Promise<ChildProfileView> {
        if (this.processError) {
            try {
                const result = await this.actor.getChild(arg0);
                return from_candid_ChildProfileView_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChild(arg0);
            return from_candid_ChildProfileView_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChildStatistics(arg0: string): Promise<{
        totalDiapers: bigint;
        totalBreastfeedingSessions: bigint;
        totalTummyTime: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getChildStatistics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChildStatistics(arg0);
            return result;
        }
    }
    async getChildrenByParent(arg0: Principal): Promise<Array<ChildProfileView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChildrenByParent(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChildrenByParent(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDiaperLogsForChild(arg0: string): Promise<Array<DiaperLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDiaperLogsForChild(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDiaperLogsForChild(arg0);
            return result;
        }
    }
    async getInviteCodes(): Promise<Array<InviteCode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInviteCodes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInviteCodes();
            return result;
        }
    }
    async getJournalNotesForChild(arg0: string): Promise<Array<JournalNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJournalNotesForChild(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJournalNotesForChild(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSharedChildren(): Promise<Array<ChildProfileView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSharedChildren();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSharedChildren();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSharedUsers(arg0: string): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSharedUsers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSharedUsers(arg0);
            return result;
        }
    }
    async getTummyTimeSessionsForChild(arg0: string): Promise<Array<TummyTimeSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTummyTimeSessionsForChild(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTummyTimeSessionsForChild(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeightEntriesForChild(arg0: string): Promise<Array<WeightEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeightEntriesForChild(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeightEntriesForChild(arg0);
            return result;
        }
    }
    async getMilkPumpingSessionsForChild(arg0: string): Promise<Array<MilkPumpingSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMilkPumpingSessionsForChild(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMilkPumpingSessionsForChild(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logDiaperChange(arg0: string, arg1: boolean, arg2: boolean, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logDiaperChange(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logDiaperChange(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async pauseBreastfeedingTimer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.pauseBreastfeedingTimer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pauseBreastfeedingTimer(arg0);
            return result;
        }
    }
    async pauseTummyTimeTimer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.pauseTummyTimeTimer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pauseTummyTimeTimer(arg0);
            return result;
        }
    }
    async regenerateChildPhoto(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.regenerateChildPhoto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.regenerateChildPhoto(arg0);
            return result;
        }
    }
    async resumeBreastfeedingTimer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resumeBreastfeedingTimer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resumeBreastfeedingTimer(arg0);
            return result;
        }
    }
    async resumeTummyTimeTimer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resumeTummyTimeTimer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resumeTummyTimeTimer(arg0);
            return result;
        }
    }
    async revokeChildAccess(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeChildAccess(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeChildAccess(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchJournalNotes(arg0: string, arg1: string): Promise<Array<JournalNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchJournalNotes(arg0, arg1);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchJournalNotes(arg0, arg1);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async shareChildWithUser(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.shareChildWithUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.shareChildWithUser(arg0, arg1);
            return result;
        }
    }
    async startBreastfeedingSession(arg0: string, arg1: Variant_left_right): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startBreastfeedingSession(arg0, to_candid_variant_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startBreastfeedingSession(arg0, to_candid_variant_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async startTummyTimeSession(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startTummyTimeSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startTummyTimeSession(arg0);
            return result;
        }
    }
    async submitRSVP(arg0: string, arg1: boolean, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRSVP(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRSVP(arg0, arg1, arg2);
            return result;
        }
    }
    async toggleChildVisibility(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleChildVisibility(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleChildVisibility(arg0);
            return result;
        }
    }
    async updateJournalNote(arg0: string, arg1: string, arg2: string, arg3: NoteColor | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJournalNote(arg0, arg1, arg2, to_candid_opt_n39(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJournalNote(arg0, arg1, arg2, to_candid_opt_n39(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateWeightEntry(arg0: string, arg1: string, arg2: number, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWeightEntry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWeightEntry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_ActiveTimerState_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActiveTimerState): ActiveTimerState {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_BreastfeedingSession_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BreastfeedingSession): BreastfeedingSession {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
async function from_candid_ChildProfileView_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChildProfileView): Promise<ChildProfileView> {
    return await from_candid_record_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_JournalNote_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JournalNote): JournalNote {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_NoteColor_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NoteColor): NoteColor {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_TummyTimeTimerState_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TummyTimeTimerState): TummyTimeTimerState {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ActiveTimerState]): ActiveTimerState | null {
    return value.length === 0 ? null : from_candid_ActiveTimerState_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TummyTimeTimerState]): TummyTimeTimerState | null {
    return value.length === 0 ? null : from_candid_TummyTimeTimerState_n21(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: bigint;
    pausedAt: [] | [bigint];
    userId: Principal;
    isPaused: boolean;
    side: {
        left: null;
    } | {
        right: null;
    };
    totalPausedDuration: bigint;
    childId: string;
}): {
    startTime: bigint;
    pausedAt?: bigint;
    userId: Principal;
    isPaused: boolean;
    side: Variant_left_right;
    totalPausedDuration: bigint;
    childId: string;
} {
    return {
        startTime: value.startTime,
        pausedAt: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.pausedAt)),
        userId: value.userId,
        isPaused: value.isPaused,
        side: from_candid_variant_n19(_uploadFile, _downloadFile, value.side),
        totalPausedDuration: value.totalPausedDuration,
        childId: value.childId
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: bigint;
    pausedAt: [] | [bigint];
    userId: Principal;
    isPaused: boolean;
    totalPausedDuration: bigint;
    childId: string;
}): {
    startTime: bigint;
    pausedAt?: bigint;
    userId: Principal;
    isPaused: boolean;
    totalPausedDuration: bigint;
    childId: string;
} {
    return {
        startTime: value.startTime,
        pausedAt: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.pausedAt)),
        userId: value.userId,
        isPaused: value.isPaused,
        totalPausedDuration: value.totalPausedDuration,
        childId: value.childId
    };
}
async function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    birthDate: bigint;
    name: string;
    sharedWith: Array<Principal>;
    isPublic: boolean;
    photo: [] | [_ExternalBlob];
    parent: Principal;
}): Promise<{
    id: string;
    birthDate: bigint;
    name: string;
    sharedWith: Array<Principal>;
    isPublic: boolean;
    photo?: ExternalBlob;
    parent: Principal;
}> {
    return {
        id: value.id,
        birthDate: value.birthDate,
        name: value.name,
        sharedWith: value.sharedWith,
        isPublic: value.isPublic,
        photo: record_opt_to_undefined(await from_candid_opt_n26(_uploadFile, _downloadFile, value.photo)),
        parent: value.parent
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: bigint;
    duration: bigint;
    side: {
        left: null;
    } | {
        right: null;
    };
    childId: string;
}): {
    startTime: bigint;
    duration: bigint;
    side: Variant_left_right;
    childId: string;
} {
    return {
        startTime: value.startTime,
        duration: value.duration,
        side: from_candid_variant_n19(_uploadFile, _downloadFile, value.side),
        childId: value.childId
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    createdAt: bigint;
    color: _NoteColor;
    text: string;
    childId: string;
    updatedAt: bigint;
}): {
    createdAt: bigint;
    color: NoteColor;
    text: string;
    childId: string;
    updatedAt: bigint;
} {
    return {
        createdAt: value.createdAt,
        color: from_candid_NoteColor_n37(_uploadFile, _downloadFile, value.color),
        text: value.text,
        childId: value.childId,
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    left: null;
} | {
    right: null;
}): Variant_left_right {
    return "left" in value ? Variant_left_right.left : "right" in value ? Variant_left_right.right : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blue: null;
} | {
    pink: null;
} | {
    purple: null;
} | {
    green: null;
} | {
    yellow: null;
}): NoteColor {
    return "blue" in value ? NoteColor.blue : "pink" in value ? NoteColor.pink : "purple" in value ? NoteColor.purple : "green" in value ? NoteColor.green : "yellow" in value ? NoteColor.yellow : value;
}
async function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChildProfileView>): Promise<Array<ChildProfileView>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ChildProfileView_n24(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BreastfeedingSession>): Array<BreastfeedingSession> {
    return value.map((x)=>from_candid_BreastfeedingSession_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JournalNote>): Array<JournalNote> {
    return value.map((x)=>from_candid_JournalNote_n35(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_NoteColor_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NoteColor): _NoteColor {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NoteColor | null): [] | [_NoteColor] {
    return value === null ? candid_none() : candid_some(to_candid_NoteColor_n10(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n9(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NoteColor): {
    blue: null;
} | {
    pink: null;
} | {
    purple: null;
} | {
    green: null;
} | {
    yellow: null;
} {
    return value == NoteColor.blue ? {
        blue: null
    } : value == NoteColor.pink ? {
        pink: null
    } : value == NoteColor.purple ? {
        purple: null
    } : value == NoteColor.green ? {
        green: null
    } : value == NoteColor.yellow ? {
        yellow: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_left_right): {
    left: null;
} | {
    right: null;
} {
    return value == Variant_left_right.left ? {
        left: null
    } : value == Variant_left_right.right ? {
        right: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
